dddd
<table id="applications_table" class="table table-bordered dataTable">
	<thead>
    	<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Surname</th>
			<th>Tel</th>
			<th>Email</th>
			<th>Matric</th>
			<th>N2</th>
			<th>ID</th>
			<th>CV</th>
			<th>Status</th>
			<th>Date</th>
			<th>Edit</th>
			<th>Delete</th>
    	</tr>
    </thead>
	<tbody>
	</tbody>
</table>